config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

class Article < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        respond_to  do |delete|
            delete.html {redirect_to articles_url, notice: "The article was successfully deleted" }
        end
    end

    def create
        @create_item = Article.new(params.require(:article).permit(:title, :body))

        respond_to (@article) do |create|
            if @create_item.save
                create.html {redirect_to @create_item, notice: 'The article has been created correctly'}
                create.json { render :show, status: :created, location: @create_item }
            else
                create.html(render :new)
                create.json { render json: @create_item.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        @update_item =  Article.find(params[:id])

        respond_to (@article) do |update|
            if @update_item.update(params.require(:article).permit(:title, :body))
                update.html {redirect_to edit_article_path, notice: 'The article has been updated correctly'}
            else
                create.html(render :edit)
            end
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<h3>Post a Comment</h3>
<p>(Comment form will go here)</p>

app/views/articles/edit.html.erb
<h1>Please Edit your page here</h1>

<%= form_for(@article) do |form| %>
  
  <div class="label">
    <%= form.label :Your_Title %>
    <%= form.text_field :title %>
  </div>

  <div class="message">
    <%= form.label :Your_Message %>
    <%= form.text_area :body %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

<br>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/index.html.erb
<h1>Welcome to all articles pages</h1>

<%= link_to "Create a New Article", new_article_path %>
<% @articles.each do |article| %>
    <h2><%= link_to article.title, article_path(article), class: 'article_title'%></h2>
    <p><%=article.body%></p><br>
    <%= link_to "Edit this post", edit_article_path(article.id)%><br>
    <%= link_to "Delete this post", article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/articles/new.html.erb
<h1>Create New Article Here</h1>

<%= form_for(@article) do |form| %>
  
  <div class="label">
    <%= form.label :Your_Title %>
    <%= form.text_field :title %>
  </div>

  <div class="message">
    <%= form.label :Your_Message %>
    <%= form.text_area :body %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h6 id="notice"><%= notice %></h6>
<h2><%=@article.title%></h2>
<p><%=@article.body%></p>
<br>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>